IfAndForLoop ifl = new IfAndForLoop();
system.debug(ifl.phone('2124443434'));
system.debug(ifl.phone('2164443434'));
system.debug(ifl.phone('3124443434'));
system.debug(ifl.phone('0124443434'));
system.debug(ifl.phone('00124443434'));
system.debug(ifl.phone('ABCDABCD'));

//1den n e
IfAndForLoop ifl2 = new IfAndForLoop();
ifl2.sum(16);

IfAndForLoop ifl3 = new IfAndForLoop();
system.debug(ifl3.hello('batch16'));