Dog d = new Dog();
system.debug('Dog name is '+d.name+', Dog color is '+d.color+ ', Dog age is '+ d.age);

Dog d1 =new Dog('Bruno', 'Black', 6);
system.debug('Dog name is '+d1.name+', Dog color is '+d1.color+ ', Dog age is '+ d1.age);

Dog d2 = new Dog();
system.debug('Dog name is '+d2.name+', Dog color is '+d2.color+ ' Dog age is '+ d2.age);

Dog d3 =new Dog('Mojo', 'Brown', 2);
system.debug('Dog name is '+d3.name+', Dog color is '+d3.color+ ', Dog age is '+ d3.age);